### ISSUE TITLE
Related to MD5SUM

### ISSUE THREAD

**Issue by atulpal1988** [DandechaAnkur/MultiPartSCPDownload#1]
Hi Ankur,
              as you are using md5sum for checking the integrity of big file(input file and output file). but md5sum is not advisable for large file. please check this link and hopefully you will understand.

https://security.stackexchange.com/questions/19906/is-md5-considered-insecure

Thanks
Atul P

**Comment by DandechaAnkur** [comment]
ok thanks bro
instead of *md5sum* there's *shasum*

**Comment by DandechaAnkur** [comment]
my main intention is not more on security
rather quickness of checking file integrity
that the file downloaded without accidental modifications
because md5 or sha any will take longer time
we should use whatever is faster
idk what is faster algo
but we should use fastest algo to quickly tell download is successful

**Comment by DandechaAnkur** [comment]
nice info bro
for hackers to create md5 passwords fast
but you understood my intention too right?
for using md5
because it is considered faster algo
thanks

**Comment by atulpal1988** [comment]
Yes,
If i will find algo who can perform integrity check of src with destn file
after copied i will let you know also.

Thanks
Atul Pal
